apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod

spec:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    # command overrides docker entrypoint instrution
    command: ["sleep.2.0"]
    # arg field overrides docker cmd instruction
    args: ["10"]
